version: '3.8'

services:
  nextjsfrontend-container:
    image: ansalemocontainerregistry.azurecr.io/nextjsfrontend:v3
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_URL_API=${NEXT_PUBLIC_URL_API}

  dotnetcoreapi-container:
    image: ansalemocontainerregistry.azurecr.io/dotnetcoreapi:v3
    ports:
      - "5000:5000"